### ISSUE TITLE
Refactoring ipynb #1 

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/dirac-dev#1]
Some of the notebooks do not follow PEP8 styling guidelines and also need refactoring.

**Comment by RajRajeshwari** [comment]
Hey @ucalyptus I would like to take up PEP8 styling.

**Comment by ucalyptus** [comment]
@RajRajeshwari Okay
Feel free to connect in need of any assistance, thank you :+1:

**Comment by ucalyptus** [comment]
Unassigning so that it is welcome to all.

**Comment by whokilleddb** [comment]
Hi , I would like to help.

**Comment by ucalyptus** [comment]
1. choose any notebook
2. refactor
3. make a PR.
if you want an example of how things should be done? 
Follow this example -> https://github.com/ucalyptus/Detecting-Ships 
Have a look at how the ipynb there is refactored into separate python files.

**Comment by ucalyptus** [comment]
For tutorials on refactoring , follow this -> https://www.youtube.com/watch?v=D_6ybDcU5gc
