### ISSUE TITLE
Usage of https://www.extracttable.com/

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/dirac-dev#6]
https://www.extracttable.com/ enables extracting tables from pdf documents.
We could display a tutorial in this repo for the same.
Employ:
1. a notebook for the same.
2. a financial document with table(s)

**Comment by hardik-dadhich** [comment]
Hi @ucalyptus, Can I look into it ?? if yes Can you give me little description for more clarification?

**Comment by ucalyptus** [comment]
We need a tutorial of how extracttable works:
1. It's a jupyter notebook which shows the usage
2. The tutorial will use a financial document
I shall supply a link to sample doc.
Any one taking up this issue will have to create a demo tutorial.ipynb using that doc and how extracttable extracts tables from that pdf document.

**Comment by ucalyptus** [comment]
A lesser pages  version of this works ->  https://report.adidas-group.com/fileadmin/user_upload/adidas_Annual_Report_GB-2018-EN.pdf

**Comment by hardik-dadhich** [comment]
Well @ucalyptus,
 I have downloaded this doc "adidas_Annual_Report_GB-2018-EN.pdf" but it is exceeding file size ? can you provide some other doc if possible or I can use any other doc with tabular content like this  for testing purpose!

<img width="1101" alt="Screenshot 2019-10-14 at 5 27 50 PM" src="https://user-images.githubusercontent.com/25060629/66749635-fc382d80-eea7-11e9-9422-1dcd92f70a61.png">

**Comment by hardik-dadhich** [comment]
Also, I am new to open source contribution so I am trying to understand your requirements. so I can use any python module(ex : Tabula, PyPDF2) for demonstration of working "extractable". Am i right :)

**Comment by ucalyptus** [comment]
@hardik-dadhich Hardik you can use any other document which has tables .
Yes you can use PyPDF2 but make a comparative analysis on how both these are different . 
Put both of them in the same notebook and do the comparison.
